- name: "condition play"
  hosts: controler
  vars:
    ulist:
      - jack
      - adi
      - ved
      - ram
      - jay
    users:
      - jack
      - mage
      - ram
      - raj
      - aru
  tasks:
    - name: "adding users by condition"
      user:
        name: "{{item}}"
        state: present
      loop: "{{users}}"
      when: item == "raj" or item == "aru"
    - name: "adding user by condition"
      user:
        name: "{{item}}"
        state: present
      loop: "{{users}}"
      when: item == "mage"
      tags:
        - cond
    - name: "adding user by condition"
      user:
        name: "{{item}}"
        state: present
      loop:
        - soham
        - sohan
        - mohan
      when: item == "mohan"
      tags:
        - condition
    - name: "installing file by ipv4 condition"
      yum:
        name: httpd
        state: present
      when: ansible_default_ipv4.address == "172.31.33.182"
      tags:
        - ipaddr

